server:
  port: 8800
spring:
  application:
    name: starrysea-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StarSeaProject/ss_config
          username: kuma_loveliver@163.com
          password: fsxjl2017
encrypt:
  key-store: 
    location: classpath:/server.jks
    password: starrysea
    alias: starrysea
    secret: starrysea