server:
  port: 8888
spring:
  application:
    name: starrysea-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StarSeaProject/ss_config
          username: kuma_loveliver@163.com
          password: fsxjl2017