server:
  port: 8010
spring: 
  application:
    name: starrysea-activity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true